# .github/workflows/pr-event.yml
name: PR Event Trigger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger-other-action:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another repository action
        run: |
          curl -X POST \
              -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/brav999/plannn-tests/actions/workflows/playwright.yml/dispatches \
              -d '{"ref":"main", "inputs": {}}'
